name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for .NET projects
      run: |
        dotnet restore TimeTracker.Core/TimeTracker.Core.csproj
        dotnet restore TimeTracker.Domain/TimeTracker.Domain.csproj
        dotnet restore TimeTracker.Infrastructure/TimeTracker.Infrastructure.csproj
        dotnet restore TimeTracker.Jira/TimeTracker.Jira.csproj
        dotnet restore TimeTrackerApi/TimeTrackerApi.csproj
    
    - name: Build .NET projects
      run: |
        dotnet build TimeTracker.Core/TimeTracker.Core.csproj --no-restore
        dotnet build TimeTracker.Domain/TimeTracker.Domain.csproj --no-restore
        dotnet build TimeTracker.Infrastructure/TimeTracker.Infrastructure.csproj --no-restore
        dotnet build TimeTracker.Jira/TimeTracker.Jira.csproj --no-restore
        dotnet build TimeTrackerApi/TimeTrackerApi.csproj --no-restore
    
    - name: Test .NET projects
      run: |
        dotnet test TimeTracker.Core/TimeTracker.Core.csproj --no-build --verbosity normal
        dotnet test TimeTracker.Domain/TimeTracker.Domain.csproj --no-build --verbosity normal
        dotnet test TimeTracker.Infrastructure/TimeTracker.Infrastructure.csproj --no-build --verbosity normal
        dotnet test TimeTracker.Jira/TimeTracker.Jira.csproj --no-build --verbosity normal
        dotnet test TimeTrackerApi/TimeTrackerApi.csproj --no-build --verbosity normal
