name: Build and deploy ASP.Net Core app to Azure Web App - timetracker-2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release TimeTrackerApi/TimeTrackerApi.sln

      - name: dotnet publish
        run: dotnet publish TimeTrackerApi/TimeTrackerApi.sln -c Release -o ${{env.DOTNET_ROOT}}/TimeTrackerApi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/TimeTrackerApi

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C0BB532123F44F8CA52DE8F30A4D4921 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_54822CCF85DB4D7C9D9F2853B2A6AFC6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C1C045A519F24CC4A2147429EAE0D89A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'timetracker-2'
          slot-name: 'Production'
          package: .
